# Generated by Django 4.1 on 2022-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(max_length=100)),
                ('pronostico', models.CharField(max_length=100)),
                ('cuota', models.IntegerField()),
            ],
        ),
    ]
